name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  MACOSX_DEPLOYMENT_TARGET: '14.0'

jobs:
  build:
    name: Ruby ${{ matrix.ruby }} Specs
    runs-on: macos-14

    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.1", "3.2", "3.3", "3.4"]

    steps:
      - uses: actions/checkout@v4

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 15.0.1

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version:  ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run tests
        run: bundle exec rspec
